version: "3.8"
services:
    database:
        build: ./database/
        ports:
        - target: 3306
          published: 3306
          protocol: tcp
        enviroment:
        - MYSQL_ROOT_PASSWORD=${PASSWORD}
    backend:
        build: ./backend/
        ports:
        - target: 5001
          published: 5001
          protocol: tcp
        enviroment:
        - PASSWORD=${PASSWORD}
    frontend:
        build: ./frontend/
        ports:
        - target: 5000
          published: 5000
          protocol: tcp
    nginx:
        image: nginx:latest
        ports:
        - target: 80
          published: 80
          protocol: tcp
        volumes:
        - type: bind
          source: ./nginx.conf
          target: /etc/nginx/nginx.conf
